export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

export const CONFIG_LOAD_SUCCESS = "CONFIG_LOAD_SUCCESS";
export const CONFIG_LOAD_ERROR = "CONFIG_LOAD_ERROR";

export const SHOW_SNACK = "SHOW_SNACK";
export const CLEAR_SNACK = "CLEAR_SNACK";

export const AUTH_LOADING = "AUTH_LOADING";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_ERROR = "REFRESH_TOKEN_ERROR";
export const FORGOTTEN_COMPLETE = "FORGOTTEN_COMPLETE";
export const CHECK_PASSWORD_RESET_TOKEN_SUCCESS = "CHECK_PASSWORD_RESET_TOKEN_SUCCESS";
export const CHECK_PASSWORD_RESET_TOKEN_ERROR = "CHECK_PASSWORD_RESET_TOKEN_ERROR";
export const PASSWORD_RESET_COMPLETE = "PASSWORD_RESET_COMPLETE";
export const PASSWORD_RESET_ERROR = "PASSWORD_RESET_ERROR";

export const CREATE_COURSE = "CREATE_COURSE";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
